#                                                                        #
# Default routes configuration for the Security.Manager package          #
#                                                                        #
-
  name: 'Authentication'
  uriPattern: 'login(/{@action}.{@format})'
  defaults:
    '@package':    'Flow.Login'
    '@controller': 'Login'
    '@action':     'index'
    '@format':     'html'