#                                                                        #
# Default routes configuration for the Refactory.Login package           #
#                                                                        #
-
  name: 'Login panel'
  uriPattern: 'login'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Login'
    '@action':     'login'
    '@format':     'html'
-
  name: 'Authenticate'
  uriPattern: 'authenticate'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Login'
    '@action':     'authenticate'
    '@format':     'json'
-
  name: 'Application Signed In'
  uriPattern: 'signedin'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Login'
    '@action':     'signedIn'
    '@format':     'html'

#
# Reset password routes
#
-
  name: 'Reset request'
  uriPattern: 'password/resetrequest'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Password'
    '@action':     'resetrequest'
    '@format':     'html'
-
  name: 'Password send reset request'
  uriPattern: 'password/sendresetrequest'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Password'
    '@action':     'sendresetrequest'
    '@format':     'json'
-
  name: 'Password reset'
  uriPattern: 'password/reset'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Password'
    '@action':     'reset'
    '@format':     'html'

#
# Register account routes
#
-
  name: 'Register User'
  uriPattern: 'register/new'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Register'
    '@action':     'new'
    '@format':     'html'

-
  name: 'Cretae User'
  uriPattern: 'register/create'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Register'
    '@action':     'create'
    '@format':     'json'

-
  name: 'Account Exists'
  uriPattern: 'register/verifyaccountexists'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Register'
    '@action':     'verifyAccountExists'
    '@format':     'json'

-
  name: 'Verify user'
  uriPattern: 'user/verify'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Register'
    '@action':     'verifyUser'
    '@format':     'html'

-
  name: 'User Verified'
  uriPattern: 'user/verified'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Register'
    '@action':     'userVerified'
    '@format':     'html'

#
# Logout route
#
-
  name: 'Logout action'
  uriPattern: 'logout'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Login'
    '@action':     'logout'
    '@format':     'html'