TYPO3:
  Flow:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
              '@package': 'Refactory.Login'
              '@controller': 'Login'
              '@action': 'index'

Refactory:
  Mail:
    viewHelpers:
      partialRootPath: 'resource://BeechIt.Mail/Private/Templates/ViewHelpers/Partials/'
      templates:
        'BeechIt\Mail\ViewHelpers\MailTemplateViewHelper':
           default: 'resource://BeechIt.Mail/Private/Templates/ViewHelpers/DefaultMailTemplate.html'
           passwordResetInstruction: 'resource://BeechIt.Login/Private/Templates/Mail/PasswordResetInstruction.html'
           passwordChangeConfirmation: 'resource://BeechIt.Login/Private/Templates/Mail/PasswordChangeConfirmation.html'
           confirmationRegistration: 'resource://BeechIt.Login/Private/Templates/Mail/ConfirmationRegistration.html'
    mail:
      from:
        email: 'info@beech.it'
        name: 'Info'
  Login:
    tokenExpiration: 14400 # in seconds
    enableRegister: TRUE
#    styles:
#      - resource://Vendor.MyPackage/Public/Styles/Custom.css'
#    authenticatedRedirect:
#      packageKey: Vendor.MyPackage
#      controller: SignedIn
#      actionName: Authenticated
