Refactory:
  Login:
    partyRepositoryClassName: 'TYPO3\Party\Domain\Repository\PartyRepository'
    tokenExpiration: 14400
    translationPackageKey: Refactory.Login
    translationSourceName: Main
TYPO3:
  Flow:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: WebRedirect
            entryPointOptions:
              routeValues: null
              '@package': Refactory.Login
              '@controller': Login
              '@action': index
